before_all do
    ensure_git_branch(
        branch: ENV["GIT_BRANCH"]
    )
    repo_clean = `git status --porcelain`.empty?
    if !repo_clean
        git_add(path: ".")
        git_commit(path: '.', message: 'commit all files')
    end
    git_pull
    push_to_git_remote
    ensure_git_status_clean
end

platform :ios do
    lane :build do
        xcode_select("/Applications/Xcode.app")
        cocoapods(podfile: "./ios/Podfile")
        repo_clean = `git status --porcelain`.empty?
        if !repo_clean  
            git_commit(path: '.', message: 'commit Pods project')
        end
        git_pull
        push_to_git_remote
        gym(
            scheme: ENV["IOS_TARGET"], 
            workspace: './ios/ProjectName.xcworkspace', #change it with your appname after proj generation
            export_method: ENV["IOS_EXPORT_METHOD"], 
            clean: true,
            output_directory: './builds'
        )
    end

    lane :addTag do
        add_git_tag(tag: 'build_' + ENV["IOS_VERSION_NAME"] + '_' + ENV["ENVIRONMENT"])
        push_to_git_remote
    end

    lane :beta do
        build
        addTag
        appcenter_upload(
            api_token: ENV["APPCENTER_API_TOKEN"],
            owner_name: ENV["APPCENTER_OWNER_NAME"],
            owner_type: ENV["APPCENTER_OWNER_TYPE"],
            app_name: ENV["APPCENTER_APP_NAME_IOS"],
            ipa: ENV["IPA_PATH"],
            notify_testers: true,
            destinations: ENV["DESTINATIONS"]
        )
    end
end

platform :android do
    lane :build do
        gradle(task: 'clean', project_dir: 'android/')
        sh "npm run build-android-release-" + ENV["ENVIRONMENT"]
    end

    lane :beta do
        build
        appcenter_upload(
            api_token: ENV["APPCENTER_API_TOKEN"],
            owner_name: ENV["APPCENTER_OWNER_NAME"],
            owner_type: ENV["APPCENTER_OWNER_TYPE"],
            app_name:  ENV["APPCENTER_APP_NAME_ANDROID"],
            apk: ENV["APK_PATH"],
            notify_testers: true,
            destinations: ENV["DESTINATIONS"]
        )
    end
end